version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.m2:/home/vscode/.m2:cached
      - ~/.azure:/home/vscode/.azure:cached
    command: sleep infinity
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_HOME=/usr/lib/jvm/msopenjdk-current
      - MAVEN_HOME=/usr/share/maven
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - techbookstore-network

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: techbookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - techbookstore-network

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - techbookstore-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    networks:
      - techbookstore-network

networks:
  techbookstore-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  azurite-data:
